type Media {
  id         : ID!
  name       : String
  caption    : String
  description: String
  altText    : String
  path       : String!
  url        : String!
  meta       : String
  mimeType   : String!
  ownerId    : Int
  thumb(size : MediaThumbSize): MediaThumb @field(resolver: "App\\GraphQL\\Resolvers\\MediaThumbResolver@get")
  thumbs: [MediaThumb] @all
}

type MediaThumb {
  id      : ID!
  path    : String!
  url     : String!
  meta    : String
  mimeType: String
  parentId: ID
}

